export const lightTheme = {
    common: {
        primaryColor: '#4a60e8',
        primaryColorHover: '#5772FF',
        primaryColorPressed: '#3d50c9',
        primaryColorSuppl: '#5772FF',
        bodyColor: '#f5f6fa',
        cardColor: '#ffffff',
        popoverColor: '#ffffff',
        modalColor: '#ffffff',
        tableColor: '#ffffff',
        textColorBase: '#1a1d2e',
        textColor1: '#1a1d2e',
        textColor2: '#44485a',
        textColor3: '#6b7082',
    },
    Button: {
        colorPrimary: 'var(--jm-primary-1)',
        textColorPrimary: '#ffffff',
        textColorHoverPrimary: '#ffffff',
        textColorPressedPrimary: '#ffffff',
        textColorFocusPrimary: '#ffffff',
        colorPressedPrimary: 'var(--jm-primary-1)',
        colorHoverPrimary: 'var(--jm-primary-2)',
        colorDisabledPrimary: 'var(--jm-primary-1)',
        borderPrimary: '1px solid var(--jm-primary-1)',
        borderHoverPrimary: '1px solid var(--jm-primary-2)',
        borderPressedPrimary: '1px solid var(--jm-primary-1)',
        borderFocusPrimary: '1px solid var(--jm-primary-1)',
        borderDisabledPrimary: '1px solid var(--jm-primary-1)',
        fontWeight: '400',
        heightSmall: '28px',
        fontSizeSmall: '12px',
        paddingSmall: '0 8px',
        heightMedium: '34px',
        paddingMedium: '5px 18px',
        fontSizeMedium: '12px',
        heightLarge: '40px',
        paddingLarge: '9px 26px',
        fontSizeLarge: '14px',
        colorWarning: 'var(--jm-primary-1)',
        colorHoverWarning: 'var(--jm-primary-2)',
        colorPressedWarning: 'var(--jm-primary-1)',
        textColorWarning: '#ffffff',
        textColorHoverWarning: '#ffffff',
        borderWarning: '1px solid var(--jm-primary-1)',
        borderHoverWarning: '1px solid var(--jm-primary-1)',
        colorInfo: 'var(--jm-primary-1)',
        colorHoverInfo: 'var(--jm-primary-2)',
        textColorInfo: '#ffffff',
        textColorHoverInfo: '#ffffff',
        borderInfo: '1px solid var(--jm-primary-1)',
        borderHoverInfo: '1px solid var(--jm-primary-1)',
        colorSuccess: 'var(--jm-primary-1)',
        colorHoverSuccess: 'var(--jm-primary-2)',
        textColorSuccess: '#ffffff',
        textColorHoverSuccess: '#ffffff',
        borderSuccess: '1px solid var(--jm-primary-1)',
        borderHoverSuccess: '1px solid var(--jm-primary-1)',
        colorError: 'var(--jm-primary-1)',
        colorHoverError: 'var(--jm-primary-2)',
        textColorError: '#ffffff',
        textColorHoverError: '#ffffff',
        borderError: '1px solid var(--jm-primary-1)',
        borderHoverError: '1px solid var(--jm-primary-1)',
        textColorDisabled: '#ffffff',
        textColorDisabledPrimary: '#ffffff',
    },
    Select: {
        menuBoxShadow: '0 2px 12px rgba(0,0,0,0.08)',
        peers: {
            InternalSelection: {
                fontWeight: '400',
                fontSizeMedium: '13px',
                placeholderColor: 'var(--jm-accent-4)',
                borderRadius: '4px',
                color: '#ffffff',
                textColor: 'var(--jm-accent-7)',
                border: '1px solid var(--jm-accent-2)',
                paddingSingle: '10px',
            },
            InternalSelectMenu: {
                fontWeight: '400',
                optionFontSizeMedium: '13px',
                optionHeightMedium: '34px',
                color: '#ffffff',
                optionTextColorHover: 'var(--jm-accent-7)',
                optionTextColor: 'var(--jm-accent-7)',
                border: '1px solid var(--jm-accent-2)',
                borderRadius: '4px',
            },
        },
    },
    Input: {
        heightMedium: '34px',
        fontSizeMedium: '12px',
        borderRadius: '4px',
        border: '1px solid var(--jm-accent-2)',
        color: '#ffffff',
        textColor: 'var(--jm-accent-7)',
        placeholderColor: 'var(--jm-accent-4)',
        caretColor: 'var(--jm-primary-1)',
        colorFocus: '#ffffff',
    },
    InputNumber: {
        heightMedium: '34px',
        fontSizeMedium: '12px',
    },
    Dialog: {
        color: '#ffffff',
        iconColorError: 'var(--jm-error-color)',
        iconColorWarning: 'var(--jm-warning-color)',
        iconColorSuccess: 'var(--jm-success-color)',
        iconColorInfo: 'var(--jm-primary-1)',
    },
    Message: {
        iconColorSuccess: 'var(--jm-success-color)',
        iconColorWarning: 'var(--jm-warning-color)',
        iconColorError: 'var(--jm-error-color)',
        iconColorInfo: 'var(--jm-primary-1)',
        borderRadius: '8px',
        textColor: 'var(--jm-accent-7)',
    },
    Card: {
        color: '#ffffff',
        borderColor: 'var(--jm-accent-2)',
        textColor: 'var(--jm-accent-7)',
        titleTextColor: 'var(--jm-accent-7)',
    },
    Modal: {
        color: '#ffffff',
        textColor: 'var(--jm-accent-7)',
        boxShadow: '0 4px 24px rgba(0,0,0,0.12)',
    },
    Switch: {
        railColor: 'var(--jm-accent-3)',
        railColorActive: 'var(--jm-primary-1)',
        loadingColor: 'var(--jm-primary-1)',
    },
    Tooltip: {
        color: 'rgba(30,30,50,0.92)',
        textColor: '#ffffff',
        padding: '4px 8px',
        borderRadius: '4px',
        boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
    },
    Dropdown: {
        color: '#ffffff',
        optionTextColor: 'var(--jm-accent-7)',
        dividerColor: 'var(--jm-accent-2)',
        borderRadius: '8px',
        boxShadow: '0 4px 16px rgba(0,0,0,0.1)',
    },
    Tag: {
        color: 'var(--jm-accent-1)',
        textColor: 'var(--jm-accent-7)',
        borderColor: 'var(--jm-accent-2)',
    },
    Steps: {
        headerTextColorProcess: 'var(--jm-accent-7)',
        headerTextColorFinish: 'var(--jm-accent-6)',
        headerTextColorWait: 'var(--jm-accent-4)',
        indicatorColorProcess: 'var(--jm-primary-1)',
        indicatorTextColorProcess: '#ffffff',
        indicatorBorderColorProcess: 'var(--jm-primary-1)',
        indicatorColorFinish: 'var(--jm-primary-1)',
        splitorColorProcess: 'var(--jm-primary-1)',
        descriptionTextColorProcess: 'var(--jm-accent-5)',
        descriptionTextColorFinish: 'var(--jm-accent-5)',
        descriptionTextColorWait: 'var(--jm-accent-4)',
    },
    Progress: {
        fillColor: 'var(--jm-primary-1)',
        railColor: 'var(--jm-accent-2)',
    },
    Form: {
        labelTextColor: 'var(--jm-accent-6)',
        feedbackTextColorError: 'var(--jm-error-color)',
    },
    Spin: {
        color: 'var(--jm-primary-1)',
    },
    Result: {
        titleTextColor: 'var(--jm-accent-7)',
        textColor: 'var(--jm-accent-6)',
    },
}
